# https://golangci-lint.run/docs/configuration/file/
version: "2"
run:
  go: "1.24"
  timeout: 3m
formatters:
  enable:
    - gofmt
linters:
  enable:
    - govet
    - revive
    - gosec
  settings:
    revive:
      # https://golangci-lint.run/docs/linters/configuration/#revive
      rules:
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#package-comments
        - name: package-comments
          severity: warning
          disabled: true
          exclude: [""]
